Repository boostcampwm-2024/web17-juchumjuchum, pull requests merged in 2024-12, with the labels that each got.

#306 Feature/#266 - 주식 정보에 단위 추가
  packages/frontend/src/components/ui/input/Input.tsx
  packages/frontend/src/constants/metricDetail.ts
  packages/frontend/src/pages/stock-detail/AddAlarmForm.tsx
  packages/frontend/src/pages/stocks/components/StockIndexCard.tsx
  packages/frontend/src/pages/stocks/components/StockInfoCard.tsx
Labels: ✨feature, FE

#307 Feature/#304 - ts-mockito 적용
  .eslintrc.js
  packages/backend/package.json
  packages/backend/src/chat/like.service.spec.ts
  packages/backend/src/scraper/korea-stock-info/korea-stock-info.service.spec.ts
  packages/backend/src/stock/stock.service.spec.ts
  packages/backend/src/stock/stockDetail.service.spec.ts
  packages/backend/src/stock/stockDetail.service.ts
  yarn.lock
Labels: :white_check_mark: test, BE

#313 Feature/#12 - 알림 구현
  packages/backend/package.json
  packages/backend/src/alarm/alarm.controller.ts
  packages/backend/src/alarm/alarm.module.ts
  packages/backend/src/alarm/alarm.service.ts
  packages/backend/src/alarm/alarm.subscriber.ts
  packages/backend/src/alarm/domain/alarm.entity.ts
  packages/backend/src/alarm/domain/subscription.entity.ts
  packages/backend/src/alarm/dto/alarm.request.ts
  packages/backend/src/alarm/dto/alarm.response.ts
  packages/backend/src/alarm/dto/subscribe.request.ts
  packages/backend/src/alarm/dto/subscribe.response.ts
  packages/backend/src/alarm/push.controller.ts
  packages/backend/src/alarm/push.service.ts
  packages/backend/src/main.ts
  packages/backend/src/scraper/openapi/api/openapiFluctuationData.api.ts
  packages/backend/src/scraper/openapi/api/openapiToken.api.ts
  packages/backend/src/scraper/openapi/openapi-scraper.module.ts
  packages/backend/src/stock/domain/stock.entity.ts
  packages/backend/src/stock/stock.module.ts
  packages/backend/src/stock/stockLiveData.subscriber.ts
  packages/backend/src/user/domain/user.entity.ts
  yarn.lock
Labels: ✨feature, BE

#316 Feature/#312 - 기간 별 데이터와 지수 데이터 큐 적용
  packages/backend/src/scraper/openapi/api/openapiIndex.api.ts
  packages/backend/src/scraper/openapi/api/openapiPeriodData.api.ts
  packages/backend/src/scraper/openapi/queue/openapi.queue.ts
Labels: ✨feature, BE

#320 docs: 리드미 서비스 특징, 주요 기능, 아키텍처, 기술스택, 실행방법 추가
  README.md
Labels: :page_with_curl: docs

#317 Feature/#102 - 채팅 무한스크롤 구현
  packages/frontend/package.json
  packages/frontend/src/apis/queries/auth/schema.ts
  packages/frontend/src/apis/queries/chat/schema.ts
  packages/frontend/src/apis/queries/chat/useGetChatList.ts
  packages/frontend/src/assets/like.svg
  packages/frontend/src/components/layouts/search/SearchResults.tsx
  packages/frontend/src/components/ui/loader/Loader.tsx
  packages/frontend/src/components/ui/loader/index.ts
  packages/frontend/src/components/ui/modal/Modal.tsx
  packages/frontend/src/constants/chatPlaceholder.ts
  packages/frontend/src/constants/chatStatus.ts
  packages/frontend/src/hooks/useInfiniteScroll.ts
  packages/frontend/src/pages/stock-detail/AddAlarmForm.tsx
  packages/frontend/src/pages/stock-detail/ChatPanel.tsx
  packages/frontend/src/pages/stock-detail/StockDetail.tsx
  packages/frontend/src/pages/stock-detail/StockMetricsPanel.tsx
  packages/frontend/src/pages/stock-detail/TradingChart.tsx
  packages/frontend/src/pages/stock-detail/components/ChatMessage.tsx
  packages/frontend/src/pages/stock-detail/components/StockDetailHeader.tsx
  packages/frontend/src/pages/stocks/Stocks.tsx
  packages/frontend/src/sockets/schema.ts
  packages/frontend/src/utils/formatDate.ts
  packages/frontend/tailwind.config.ts
  yarn.lock
Labels: 📪API, FE

#328 🐛 fix: gateway subscribe, unsubscribe 에러 수정
  packages/backend/src/stock/stock.gateway.ts
Labels: :lady_beetle: bugfix, BE

#330 Bug/#326 - 세션 직렬화 방식 변경
  packages/backend/src/auth/session/session.serializer.ts
  packages/backend/src/auth/session/webSocketSession.guard.ts
  packages/backend/src/auth/session/websocketSession.service.ts
  packages/backend/src/chat/chat.gateway.ts
  packages/backend/src/stock/stock.service.ts
  packages/backend/src/user/user.service.ts
Labels: :lady_beetle: bugfix, BE

#331 Feature/#311 - 로컬 캐시 적용 및 채팅 엔드포인트 수정
  packages/backend/src/chat/chat.controller.ts
  packages/backend/src/chat/dto/chat.request.ts
  packages/backend/src/common/cache/localCache.ts
  packages/backend/src/scraper/openapi/util/priorityQueue.ts
  packages/backend/src/stock/cache/stockData.cache.ts
  packages/backend/src/stock/stock.module.ts
  packages/backend/src/stock/stockData.service.ts
  packages/backend/src/utils/date.ts
Labels: ✨feature, BE

#333 Bug/#315 period 중복데이터 문제, 다중 계좌 priority queue 문제 해결
  packages/backend/src/scraper/openapi/api/openapiPeriodData.api.ts
  packages/backend/src/scraper/openapi/queue/openapi.queue.ts
  packages/backend/src/scraper/openapi/util/newDate.util.ts
Labels: :lady_beetle: bugfix, 🔨 refactor, BE

#335 Feature/#126 - 주식 그래프 무한스크롤 구현
  packages/frontend/src/apis/queries/stocks/useGetStocksPriceSeries.ts
  packages/frontend/src/apis/queries/user/useGetUserTheme.ts
  packages/frontend/src/components/layouts/Sidebar.tsx
  packages/frontend/src/pages/stock-detail/TradingChart.tsx
  packages/frontend/src/pages/stock-detail/hooks/useChart.ts
Labels: ✨feature, 📪API, FE

#338 Feature/#324 - 새로고침 시 다크모드 깜빡임 해결
  packages/frontend/src/components/layouts/Sidebar.tsx
  packages/frontend/src/contexts/themeContext.ts
  packages/frontend/src/contexts/themeProvider.tsx
  packages/frontend/src/pages/my-page/StockInfo.tsx
  packages/frontend/src/pages/stock-detail/hooks/useChart.ts
  packages/frontend/src/routes/index.tsx
Labels: :lady_beetle: bugfix, FE

#347 Bug/#346 - 좋아요 순 스크롤 시 다른 방 데이터 조회 문제 해결
  packages/backend/src/chat/chat.service.ts
Labels: :lady_beetle: bugfix, BE

#343 Feature/#341 분봉 리팩토링 및 장 시간대에 분봉 받아오기, alarm 한번만 작동
  packages/backend/src/alarm/alarm.service.ts
  packages/backend/src/alarm/alarm.subscriber.ts
  packages/backend/src/alarm/dto/subscribe.request.ts
  packages/backend/src/scraper/openapi/api/openapiMinuteData.api.ts
  packages/backend/src/scraper/openapi/liveData.service.ts
  packages/backend/src/scraper/openapi/type/openapiMinuteData.type.ts
Labels: :lady_beetle: bugfix, 🔨 refactor, BE

#344 Feature/#332 - 누락된 최신 차트데이터가 존재하면 API 요청 후 차트데이터 전달
  packages/backend/src/scraper/openapi/api/openapiPeriodData.api.ts
  packages/backend/src/scraper/openapi/openapi-scraper.module.ts
  packages/backend/src/scraper/openapi/type/openapiPeriodData.type.ts
  packages/backend/src/scraper/openapi/util/newDate.util.ts
  packages/backend/src/stock/constants/timeunit.ts
  packages/backend/src/stock/dto/stockData.response.ts
  packages/backend/src/stock/stock.controller.ts
  packages/backend/src/stock/stock.module.ts
  packages/backend/src/stock/stockData.service.spec.ts
  packages/backend/src/stock/stockData.service.ts
Labels: ✨feature, BE

#348 Feature/#339 - 채팅 좋아요순 정렬 적용, 채팅 줄바꿈/엔터 전송 적용
  packages/frontend/src/apis/queries/chat/index.ts
  packages/frontend/src/apis/queries/chat/schema.ts
  packages/frontend/src/apis/queries/chat/useGetChatList.ts
  packages/frontend/src/constants/metricDetail.ts
  packages/frontend/src/hooks/useInfiniteScroll.ts
  packages/frontend/src/pages/stock-detail/ChatPanel.tsx
  packages/frontend/src/pages/stock-detail/components/ChatMessage.tsx
  packages/frontend/src/pages/stock-detail/components/TextArea.tsx
  packages/frontend/src/pages/stock-detail/hooks/useChatOrder.ts
  packages/frontend/src/utils/checkChatWriter.ts
Labels: ✨feature, FE

#351 🐛 fix: join column에 user_id 이름 추가
  packages/backend/src/alarm/domain/subscription.entity.ts
Labels: :lady_beetle: bugfix, :earth_asia: deploy, BE

#352 Feature/#325 - 그래프 크기가 즉각적으로 변화하지 않는 문제 수정, 반응형 적용
  packages/frontend/src/pages/my-page/MyPage.tsx
  packages/frontend/src/pages/my-page/StockInfo.tsx
  packages/frontend/src/pages/my-page/UserInfo.tsx
  packages/frontend/src/pages/stock-detail/StockDetail.tsx
  packages/frontend/src/pages/stock-detail/StockMetricsPanel.tsx
  packages/frontend/src/pages/stock-detail/TradingChart.tsx
  packages/frontend/src/pages/stock-detail/components/MetricItem.tsx
  packages/frontend/src/pages/stock-detail/hooks/useChart.ts
  packages/frontend/src/pages/stocks/StockRankingTable.tsx
  packages/frontend/src/pages/stocks/Stocks.tsx
  packages/frontend/src/pages/stocks/components/StockIndexCard.tsx
  packages/frontend/src/pages/stocks/components/StockInfoCard.tsx
Labels: :lady_beetle: bugfix, 🎨 html&css, FE

#357 Feature/#355 - 검색어 빈 값 요청 처리, 초기 로딩 시 그래프만 다크모드인 문제 수정
  packages/frontend/src/components/layouts/search/Search.tsx
  packages/frontend/src/pages/stock-detail/hooks/useChart.ts
Labels: :lady_beetle: bugfix, FE

#359 Feature/#358 - 요청 큐 횟수 제한
  packages/backend/src/scraper/korea-stock-info/korea-stock-info.service.ts
  packages/backend/src/scraper/openapi/api/openapiPeriodData.api.ts
  packages/backend/src/scraper/openapi/queue/openapi.queue.ts
  packages/backend/src/stock/stock.controller.ts
  packages/backend/src/stock/stockData.service.ts
Labels: :lady_beetle: bugfix, ✨feature, BE

#360 Feature/#310 - 주식 메인페이지에서 웹소켓이 연결되고 있는 문제 해결
  packages/frontend/src/sockets/config.ts
  packages/frontend/src/sockets/useWebsocket.ts
Labels: :lady_beetle: bugfix, FE

#362 Bug/#361 알림 서비스 오류 해결
  packages/backend/src/alarm/alarm.controller.ts
  packages/backend/src/alarm/alarm.service.ts
  packages/backend/src/alarm/domain/alarm.entity.ts
  packages/backend/src/auth/auth.module.ts
  packages/backend/src/utils/date.ts
Labels: :lady_beetle: bugfix, BE

#363 Bug/#345 - 제약조건 에러 해결 및 각종 버그 수정
  packages/backend/src/chat/chat.service.spec.ts
  packages/backend/src/chat/domain/chat.entity.ts
  packages/backend/src/chat/dto/chat.request.ts
  packages/backend/src/chat/dto/like.response.ts
  packages/backend/src/scraper/korea-stock-info/korea-stock-info.service.spec.ts
  packages/backend/src/scraper/openapi/api/openapiDetailData.api.ts
  packages/backend/src/scraper/openapi/api/openapiPeriodData.api.ts
  packages/backend/src/scraper/openapi/api/openapiToken.api.ts
  packages/backend/src/scraper/openapi/util/priorityQueue.ts
  packages/backend/src/scraper/openapi/util/queue.spec.ts
  packages/backend/src/stock/cache/stockData.cache.ts
  packages/backend/src/stock/decorator/stock.decorator.ts
  packages/backend/src/stock/decorator/stockData.decorator.ts
  packages/backend/src/stock/dto/stock.response.ts
  packages/backend/src/stock/dto/stockView.request.ts
  packages/backend/src/stock/dto/userStock.request.ts
  packages/backend/src/stock/stock.controller.ts
  packages/backend/src/stock/stock.service.spec.ts
  packages/backend/src/stock/stockData.service.ts
  packages/backend/src/stock/stockDetail.service.spec.ts
  packages/backend/src/user/domain/theme.ts
  packages/backend/src/user/dto/user.response.ts
  packages/backend/src/utils/date.ts
Labels: :lady_beetle: bugfix, ✨feature, BE

#364 Feature/#119 - 알림 추가, 확인 기능 구현, 로그인 상태 관리 추가
  packages/frontend/public/serviceWorker.js
  packages/frontend/src/apis/config/index.ts
  packages/frontend/src/apis/queries/alarm/index.ts
  packages/frontend/src/apis/queries/alarm/schema.ts
  packages/frontend/src/apis/queries/alarm/useGetAlarm.ts
  packages/frontend/src/apis/queries/alarm/useGetStockAlarm.ts
  packages/frontend/src/apis/queries/alarm/usePostCreateAlarm.ts
  packages/frontend/src/apis/queries/alarm/usePostInitAlarm.ts
  packages/frontend/src/apis/queries/auth/useGetLoginStatus.ts
  packages/frontend/src/apis/queries/user/useGetUserTheme.ts
  packages/frontend/src/components/layouts/Sidebar.tsx
  packages/frontend/src/components/ui/alarm/Alarm.tsx
  packages/frontend/src/components/ui/modal/Modal.tsx
  packages/frontend/src/constants/alarmOptions.ts
  packages/frontend/src/constants/chatStatus.ts
  packages/frontend/src/constants/modalMessage.ts
  packages/frontend/src/contexts/login/index.ts
  packages/frontend/src/contexts/login/loginContext.ts
  packages/frontend/src/contexts/login/loginProvider.tsx
  packages/frontend/src/contexts/theme/index.ts
  packages/frontend/src/contexts/theme/themeContext.ts
  packages/frontend/src/contexts/theme/themeProvider.tsx
  packages/frontend/src/hooks/useSubscribeAlarm.ts
  packages/frontend/src/mocks/alarm.json
  packages/frontend/src/mocks/market.json
  packages/frontend/src/mocks/priceData.json
  packages/frontend/src/mocks/stock.json
  packages/frontend/src/mocks/volumeData.json
  packages/frontend/src/pages/my-page/AlarmInfo.tsx
  packages/frontend/src/pages/my-page/MyPage.tsx
  packages/frontend/src/pages/my-page/StockInfo.tsx
  packages/frontend/src/pages/stock-detail/AddAlarmForm.tsx
  packages/frontend/src/pages/stock-detail/ChatPanel.tsx
  packages/frontend/src/pages/stock-detail/NotificationPanel.tsx
  packages/frontend/src/pages/stock-detail/StockDetail.tsx
  packages/frontend/src/pages/stock-detail/StockMetricsPanel.tsx
  packages/frontend/src/pages/stock-detail/TradingChart.tsx
  packages/frontend/src/pages/stock-detail/components/StockDetailHeader.tsx
  packages/frontend/src/pages/stock-detail/hooks/useChart.ts
  packages/frontend/src/routes/index.tsx
  packages/frontend/tsconfig.app.json
Labels: ✨feature, FE

#366 Feature/#365 알림 response 변경, 알림 검증 로직 추가, 중복 함수 리팩토링
  packages/backend/src/alarm/alarm.controller.ts
  packages/backend/src/alarm/alarm.service.ts
  packages/backend/src/alarm/alarm.subscriber.ts
  packages/backend/src/alarm/domain/alarm.entity.ts
  packages/backend/src/alarm/dto/alarm.request.ts
  packages/backend/src/alarm/dto/alarm.response.ts
Labels: :lady_beetle: bugfix, 🔨 refactor, BE

#372 Bug/#371 - 차트 데이터를 문자열로 변경
  packages/backend/src/stock/dto/stockData.response.ts
Labels: :lady_beetle: bugfix, BE

#375 Feature/#373 - suspense, error boundary, alarm로직 변경
  packages/frontend/package.json
  packages/frontend/src/App.tsx
  packages/frontend/src/apis/config/index.ts
  packages/frontend/src/apis/queries/alarm/schema.ts
  packages/frontend/src/apis/queries/alarm/useGetStockAlarm.ts
  packages/frontend/src/apis/queries/alarm/usePostCreateAlarm.ts
  packages/frontend/src/apis/queries/auth/useGetLoginStatus.ts
  packages/frontend/src/apis/queries/chat/useGetChatList.ts
  packages/frontend/src/apis/queries/chat/usePostChatLike.ts
  packages/frontend/src/apis/queries/errorSchema.ts
  packages/frontend/src/apis/queries/stock-detail/useGetStockDetail.ts
  packages/frontend/src/apis/queries/stocks/index.ts
  packages/frontend/src/apis/queries/stocks/useGetSearchStocks.ts
  packages/frontend/src/apis/queries/stocks/useGetStockIndex.ts
  packages/frontend/src/apis/queries/stocks/useGetStocksByPrice.ts
  packages/frontend/src/apis/queries/stocks/useGetStocksPriceSeries.ts
  packages/frontend/src/apis/queries/stocks/useGetTopViews.ts
  packages/frontend/src/apis/queries/stocks/useStockQueries.ts
  packages/frontend/src/apis/queries/user/useGetUserInfo.ts
  packages/frontend/src/apis/queries/user/useGetUserStock.ts
  packages/frontend/src/components/errors/error.tsx
  packages/frontend/src/components/layouts/Sidebar.tsx
  packages/frontend/src/components/lottie/error-loading.json
  packages/frontend/src/components/ui/alarm/Alarm.tsx
  packages/frontend/src/components/ui/loader/Loader.tsx
  packages/frontend/src/constants/menuItems.tsx
  packages/frontend/src/pages/my-page/AlarmInfo.tsx
  packages/frontend/src/pages/my-page/StockInfo.tsx
  packages/frontend/src/pages/stock-detail/AddAlarmForm.tsx
  packages/frontend/src/pages/stock-detail/ChatPanel.tsx
  packages/frontend/src/pages/stock-detail/NotificationPanel.tsx
  packages/frontend/src/pages/stock-detail/StockDetail.tsx
  packages/frontend/src/pages/stock-detail/StockMetricsPanel.tsx
  packages/frontend/src/pages/stock-detail/TradingChart.tsx
  packages/frontend/src/pages/stocks/StockRankingTable.tsx
  packages/frontend/src/pages/stocks/Stocks.tsx
  packages/frontend/src/routes/index.tsx
  yarn.lock
Labels: ✨feature, FE

#379 Bug/#377 - 그래프 데이터 버그 수정
  packages/backend/src/chat/like.service.ts
  packages/backend/src/common/cache/localCache.ts
  packages/backend/src/stock/cache/stockData.cache.ts
  packages/backend/src/stock/dto/stockData.response.ts
  packages/backend/src/stock/stockData.service.ts
Labels: :lady_beetle: bugfix, BE

#380 Feature/#378 - 쿼리 캐싱, 무효화 설정 및 자잘한 에러 수정, 스켈레톤 추가
  packages/frontend/src/apis/queries/alarm/useGetAlarm.ts
  packages/frontend/src/apis/queries/alarm/usePostCreateAlarm.ts
  packages/frontend/src/apis/queries/auth/usePostLogout.ts
  packages/frontend/src/apis/queries/chat/useGetChatList.ts
  packages/frontend/src/apis/queries/stock-detail/useGetStockDetail.ts
  packages/frontend/src/apis/queries/stock-detail/useGetStockOwnership.ts
  packages/frontend/src/apis/queries/stock-detail/usePostStockView.ts
  packages/frontend/src/apis/queries/stocks/useGetStocksByPrice.ts
  packages/frontend/src/apis/queries/stocks/useGetStocksPriceSeries.ts
  packages/frontend/src/apis/queries/user/useGetUserInfo.ts
  packages/frontend/src/apis/queries/user/useGetUserStock.ts
  packages/frontend/src/components/lottie/skeleton.json
  packages/frontend/src/components/ui/alarm/Alarm.tsx
  packages/frontend/src/contexts/theme/themeProvider.tsx
  packages/frontend/src/pages/login/Login.tsx
  packages/frontend/src/pages/my-page/StockInfo.tsx
  packages/frontend/src/pages/stock-detail/NotificationPanel.tsx
  packages/frontend/src/pages/stock-detail/StockMetricsPanel.tsx
  packages/frontend/src/pages/stocks/StockRankingTable.tsx
Labels: :lady_beetle: bugfix, FE

#384 🐛 fix: 알림 서비스 0이 들어올 때 등록되는 문제 해결
  packages/backend/src/alarm/alarm.service.ts
Labels: :lady_beetle: bugfix

#385 Feature/#381 - 자잘한 UI 에러 수정
  packages/frontend/src/apis/queries/alarm/useGetAlarm.ts
  packages/frontend/src/apis/queries/alarm/usePostCreateAlarm.ts
  packages/frontend/src/apis/queries/chat/useGetChatList.ts
  packages/frontend/src/apis/queries/stocks/useGetStocksPriceSeries.ts
  packages/frontend/src/apis/queries/user/usePatchUserTheme.ts
  packages/frontend/src/apis/queries/user/usePostUserNickname.ts
  packages/frontend/src/components/lottie/dark-skeleton.json
  packages/frontend/src/hooks/useSubscribeAlarm.ts
  packages/frontend/src/pages/login/Login.tsx
  packages/frontend/src/pages/stock-detail/AddAlarmForm.tsx
  packages/frontend/src/pages/stock-detail/ChatPanel.tsx
  packages/frontend/src/pages/stock-detail/StockDetail.tsx
  packages/frontend/src/pages/stock-detail/StockMetricsPanel.tsx
  packages/frontend/src/pages/stock-detail/TradingChart.tsx
  packages/frontend/src/pages/stock-detail/components/StockDetailHeader.tsx
  packages/frontend/src/pages/stocks/StockRankingTable.tsx
  packages/frontend/src/pages/stocks/components/StockIndexCard.tsx
Labels: :lady_beetle: bugfix

#386 Dev fe -> dev merge
  packages/frontend/src/apis/queries/alarm/useGetAlarm.ts
  packages/frontend/src/apis/queries/alarm/usePostCreateAlarm.ts
  packages/frontend/src/apis/queries/chat/useGetChatList.ts
  packages/frontend/src/apis/queries/stocks/useGetStocksPriceSeries.ts
  packages/frontend/src/apis/queries/user/usePatchUserTheme.ts
  packages/frontend/src/apis/queries/user/usePostUserNickname.ts
  packages/frontend/src/components/lottie/dark-skeleton.json
  packages/frontend/src/hooks/useSubscribeAlarm.ts
  packages/frontend/src/pages/login/Login.tsx
  packages/frontend/src/pages/stock-detail/AddAlarmForm.tsx
  packages/frontend/src/pages/stock-detail/ChatPanel.tsx
  packages/frontend/src/pages/stock-detail/StockDetail.tsx
  packages/frontend/src/pages/stock-detail/StockMetricsPanel.tsx
  packages/frontend/src/pages/stock-detail/TradingChart.tsx
  packages/frontend/src/pages/stock-detail/components/StockDetailHeader.tsx
  packages/frontend/src/pages/stocks/StockRankingTable.tsx
  packages/frontend/src/pages/stocks/components/StockIndexCard.tsx
Labels: FE
