Repository boostcampwm-2024/web17-juchumjuchum, pull requests merged in 2024-11, with the labels that each got.

#73 Docs - README.md에 서비스 개요 및 피그마 링크 추가
  README.md
Labels: :page_with_curl: docs

#131 Feature - TypeORM 의존성 설치 및 설정
  packages/backend/package.json
  packages/backend/src/app.module.ts
  packages/backend/src/configs/typeorm.config.ts
  yarn.lock
Labels: ✨feature, BE

#135 Feat/#133 - 디자인 시스템 설정
  .prettierrc
  packages/frontend/package.json
  packages/frontend/src/index.css
  packages/frontend/tailwind.config.js
  yarn.lock
Labels: 🎨 html&css, FE

#134 Feature/#5 - 개별 주식을 선택하면 조회수가 증가한다.
  packages/backend/src/app.module.ts
  packages/backend/src/stock/domain/stock.entity.ts
  packages/backend/src/stock/stock.controller.ts
  packages/backend/src/stock/stock.module.ts
  packages/backend/src/stock/stock.service.spec.ts
  packages/backend/src/stock/stock.service.ts
Labels: ✨feature, BE

#137 Feature/#7 클라이언트와 서버 실시간 연결
  packages/backend/package.json
  packages/backend/src/stock/stock.gateway.ts
  packages/backend/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: ✨feature, BE

#139 Feature/#138 - swagger 설정
  packages/backend/package.json
  packages/backend/src/configs/swagger.config.ts
  packages/backend/src/main.ts
  packages/backend/src/stock/dto/stockView.request.ts
  packages/backend/src/stock/stock.controller.ts
  yarn.lock
Labels: ✨feature, BE

#140 Feature/#14 - 사용자가 주식을 소유할 수 있다.
  packages/backend/package.json
  packages/backend/src/app.module.ts
  packages/backend/src/common/dateEmbedded.entity.ts
  packages/backend/src/configs/logger.config.ts
  packages/backend/src/main.ts
  packages/backend/src/stock/domain/stock.entity.ts
  packages/backend/src/stock/domain/userStock.entity.ts
  packages/backend/src/stock/dto/stock.Response.ts
  packages/backend/src/stock/dto/stockView.request.ts
  packages/backend/src/stock/dto/userStock.request.ts
  packages/backend/src/stock/dto/userStock.response.ts
  packages/backend/src/stock/stock.controller.ts
  packages/backend/src/stock/stock.service.spec.ts
  packages/backend/src/stock/stock.service.ts
  packages/backend/src/user/domain/ouathType.ts
  packages/backend/src/user/domain/role.ts
  packages/backend/src/user/domain/user.entity.ts
  packages/backend/src/user/user.module.ts
  packages/backend/src/user/user.service.spec.ts
  packages/backend/src/user/user.service.ts
  yarn.lock
Labels: ✨feature, BE

#143 Feature/#44 - oauth 버튼을 누르면 전용 로그인 사이트로 리다이렉트한다.
  packages/backend/package.json
  packages/backend/src/app.module.ts
  packages/backend/src/auth/auth.module.ts
  packages/backend/src/auth/google.strategy.ts
  packages/backend/src/auth/googleAuth.controller.ts
  packages/backend/src/auth/guard/google.guard.ts
  yarn.lock
Labels: ✨feature, BE

#145 chore: PR 시에 이슈 자동으로 close
  .github/workflows/close-issue.yml
Labels: ⚙setting

#146 Feature/#46 - 구글 oauth 서버로부터 access토큰을 받는다.
  packages/backend/src/auth/google.strategy.ts
  packages/backend/src/auth/googleAuth.controller.ts
  packages/backend/src/auth/guard/google.guard.ts
Labels: ✨feature, BE

#149 Feature/#48 - 구글 Oauth로부터 사용자의 정보를 받는다.
  packages/backend/src/auth/google.strategy.ts
Labels: ✨feature, BE

#147 Feat/#136 - 주식 상세 페이지 기본 UI를 구현한다.
  packages/frontend/package.json
  packages/frontend/src/App.tsx
  packages/frontend/src/assets/plus.svg
  packages/frontend/src/assets/send.svg
  packages/frontend/src/components/ui/Button.tsx
  packages/frontend/src/components/ui/index.ts
  packages/frontend/src/constants/METRIC_ITEM.ts
  packages/frontend/src/index.css
  packages/frontend/src/mocks/data.json
  packages/frontend/src/pages/stock-detail/AddAlarmForm.tsx
  packages/frontend/src/pages/stock-detail/ChatPanel.tsx
  packages/frontend/src/pages/stock-detail/NotificationPanel.tsx
  packages/frontend/src/pages/stock-detail/StockDetail.tsx
  packages/frontend/src/pages/stock-detail/StockMetricsPanel.tsx
  packages/frontend/src/pages/stock-detail/components/MetricItem.tsx
  packages/frontend/src/pages/stock-detail/components/MetricSection.tsx
  packages/frontend/src/pages/stock-detail/components/TextArea.tsx
  packages/frontend/src/pages/stock-detail/components/Title.tsx
  packages/frontend/src/pages/stock-detail/components/index.ts
  packages/frontend/src/pages/stock-detail/index.ts
  packages/frontend/src/utils/cn.ts
  packages/frontend/src/vite-env.d.ts
  packages/frontend/svg.d.ts
  packages/frontend/tailwind.config.js
  packages/frontend/tsconfig.app.json
  packages/frontend/tsconfig.node.json
  packages/frontend/vite.config.ts
  yarn.lock
Labels: 🎨 html&css, FE

#148 Feature/#15 실시간 주가 정보 제공 기능 구현
  packages/backend/src/stock/domain/stockLiveData.entity.ts
  packages/backend/src/stock/stock.gateway.ts
  packages/backend/src/stock/stock.module.ts
  packages/backend/src/stock/stockLiveData.subscriber.ts
Labels: ✨feature

#150 Feature/#49 - Oauth 로그인 시 사용자 정보가 없으면 자동 회원가입
  packages/backend/src/auth/auth.module.ts
  packages/backend/src/auth/google.strategy.ts
  packages/backend/src/auth/googleAuth.service.spec.ts
  packages/backend/src/auth/googleAuth.service.ts
  packages/backend/src/common/dateEmbedded.entity.ts
  packages/backend/src/stock/stock.service.spec.ts
  packages/backend/src/user/domain/user.entity.ts
  packages/backend/src/user/user.module.ts
  packages/backend/src/user/user.service.spec.ts
  packages/backend/src/user/user.service.ts
Labels: ✨feature, BE

#155 Feature/#153 - 사이드바 UI 구현
  packages/frontend/package.json
  packages/frontend/public/logoCharacter.png
  packages/frontend/public/logoTitle.png
  packages/frontend/src/App.tsx
  packages/frontend/src/assets/bell.svg
  packages/frontend/src/assets/home.svg
  packages/frontend/src/assets/search.svg
  packages/frontend/src/assets/stock.svg
  packages/frontend/src/assets/theme.svg
  packages/frontend/src/assets/user.svg
  packages/frontend/src/components/layouts/Layout.tsx
  packages/frontend/src/components/layouts/MenuList.tsx
  packages/frontend/src/components/layouts/Sidebar.tsx
  packages/frontend/src/components/layouts/index.ts
  packages/frontend/src/constants/menuItems.tsx
  packages/frontend/src/constants/metricItem.ts
  packages/frontend/src/pages/home/Home.tsx
  packages/frontend/src/pages/home/index.ts
  packages/frontend/src/pages/my-page/MyPage.tsx
  packages/frontend/src/pages/my-page/index.ts
  packages/frontend/src/pages/stock-detail/StockDetail.tsx
  packages/frontend/src/routes/index.tsx
  yarn.lock
Labels: ✨feature, 🎨 html&css, FE

#144 deploy v0.1 추가
  .github/workflows/deploy-backend.yml
  .github/workflows/deploy-frontend.yml
  .gitignore
  packages/backend/Dockerfile
  packages/backend/package.json
  packages/backend/src/app.controller.spec.ts
  packages/backend/src/app.controller.ts
  packages/backend/src/app.module.ts
  packages/backend/src/app.service.ts
  packages/backend/src/auth/passport/google.strategy.ts
  packages/backend/src/openapi-scraper/korea-stock-info/dto/master-download.dto.ts
  packages/backend/src/openapi-scraper/korea-stock-info/dto/master-split.dto.ts
  packages/backend/src/openapi-scraper/korea-stock-info/entities/stock.entity.ts
  packages/backend/src/openapi-scraper/korea-stock-info/korea-stock-info.controller.spec.ts
  packages/backend/src/openapi-scraper/korea-stock-info/korea-stock-info.controller.ts
  packages/backend/src/openapi-scraper/korea-stock-info/korea-stock-info.service.spec.ts
  packages/backend/src/openapi-scraper/korea-stock-info/korea-stock-info.service.ts
  packages/backend/src/openapi-scraper/openapi-scraper.controller.ts
  packages/backend/src/openapi-scraper/openapi-scraper.module.ts
  packages/backend/src/openapi-scraper/openapi-scraper.service.ts
  packages/backend/src/openapi-scraper/openapi-scraper.ts
  packages/backend/src/openapi-scraper/openapi.config.ts
  packages/backend/src/stock-price/stock-price.controller.spec.ts
  packages/backend/src/stock-price/stock-price.controller.ts
  packages/backend/src/stock-price/stock-price.module.ts
  packages/backend/tsconfig.build.json
  packages/frontend/Dockerfile
  yarn.lock
Labels: :earth_asia: deploy

#151 Feat/#127 - 차트 UI 구현
  packages/frontend/package.json
  packages/frontend/src/mocks/priceData.json
  packages/frontend/src/mocks/volumeData.json
  packages/frontend/src/pages/stock-detail/StockDetail.tsx
  packages/frontend/src/pages/stock-detail/TradingChart.tsx
  packages/frontend/src/pages/stock-detail/hooks/useChart.ts
  packages/frontend/src/pages/stock-detail/hooks/useChartResize.ts
  packages/frontend/src/styles/theme/darkTheme.ts
  packages/frontend/src/styles/theme/index.ts
  packages/frontend/src/styles/theme/lightTheme.ts
  packages/frontend/src/styles/theme/types.ts
  packages/frontend/src/utils/createChartOptions.ts
  packages/frontend/src/utils/getHistogramColorData.ts
  packages/frontend/tailwind.config.js
  yarn.lock
Labels: ✨feature, 🎨 html&css, FE

#156 Feature/#23 EPS, PER, 시가총액 등 주식 상세 정보 기능 추가
  packages/backend/src/stock/domain/stockDetail.entity.ts
  packages/backend/src/stock/domain/stockLiveData.entity.ts
  packages/backend/src/stock/dto/stockDetail.response.ts
  packages/backend/src/stock/stock.controller.ts
  packages/backend/src/stock/stock.module.ts
  packages/backend/src/stock/stockDetail.service.spec.ts
  packages/backend/src/stock/stockDetail.service.ts
  packages/backend/src/stock/stockLiveData.subscriber.ts
Labels: ✨feature, BE

#161 Feature/#160 - tooltip 컴포넌트 구현
  packages/frontend/src/components/ui/Tooltip.tsx
  packages/frontend/src/components/ui/index.ts
  packages/frontend/src/constants/METRIC_DETAILS.ts
  packages/frontend/src/mocks/data.json
  packages/frontend/src/pages/stock-detail/StockMetricsPanel.tsx
  packages/frontend/src/pages/stock-detail/components/MetricItem.tsx
  packages/frontend/src/pages/stock-detail/components/MetricSection.tsx
  packages/frontend/src/pages/stock-detail/components/Title.tsx
Labels: ✨feature, 🎨 html&css, FE

#166 Feature/#165 - favicon 아이콘 추가
  packages/frontend/index.html
  packages/frontend/public/favicon.ico
  packages/frontend/public/vite.svg
Labels: FE

#164 Feature/#162 - 스토리북 설정
  .github/workflows/storybook.yml
  packages/frontend/.gitignore
  packages/frontend/.storybook/main.ts
  packages/frontend/.storybook/preview.ts
  packages/frontend/package.json
  packages/frontend/src/components/ui/button/Button.stories.ts
  packages/frontend/src/components/ui/button/Button.tsx
  packages/frontend/src/components/ui/button/index.ts
  packages/frontend/src/components/ui/tooltip/Tooltip.stories.tsx
  packages/frontend/src/components/ui/tooltip/Tooltip.tsx
  packages/frontend/src/components/ui/tooltip/index.ts
  packages/frontend/src/pages/stock-detail/StockDetail.tsx
  packages/frontend/src/pages/stock-detail/StockMetricsPanel.tsx
  packages/frontend/src/pages/stock-detail/components/MetricItem.tsx
  yarn.lock
Labels: ✨feature, FE

#169 Bug/#168 - 스토리북 빌드되지 않는 문제 수정
  .github/workflows/deploy-frontend.yml
  .github/workflows/storybook.yml
  packages/frontend/src/components/layouts/Layout.tsx
  packages/frontend/src/pages/stock-detail/TradingChart.tsx
  packages/frontend/src/styles/theme/darkTheme.ts
  packages/frontend/src/styles/theme/lightTheme.ts
  packages/frontend/src/utils/getHistogramColorData.ts
  packages/frontend/tailwind.config.ts
  packages/frontend/tsconfig.app.json
Labels: :lady_beetle: bugfix, :earth_asia: deploy, FE

#170 Fix/#22 StockController 중복 코드 수정
  packages/backend/src/stock/stock.controller.ts
Labels: :lady_beetle: bugfix, BE

#157 Feature/#152 - 로그인한 사람들이 주식 채팅방에 참여할 수 있다.
  packages/backend/src/app.module.ts
  packages/backend/src/auth/auth.module.ts
  packages/backend/src/auth/google/googleAuth.controller.ts
  packages/backend/src/auth/google/googleAuth.service.spec.ts
  packages/backend/src/auth/google/googleAuth.service.ts
  packages/backend/src/auth/google/guard/google.guard.ts
  packages/backend/src/auth/google/strategy/google.strategy.ts
  packages/backend/src/auth/session.module.ts
  packages/backend/src/auth/session/cookieParser.ts
  packages/backend/src/auth/session/session.serializer.ts
  packages/backend/src/auth/session/webSocketSession.guard..ts
  packages/backend/src/chat/chat.gateway.ts
  packages/backend/src/chat/chat.module.ts
  packages/backend/src/chat/chat.service.ts
  packages/backend/src/chat/domain/chat.entity.ts
  packages/backend/src/chat/domain/chatType.enum.ts
  packages/backend/src/configs/devTypeormConfig.ts
  packages/backend/src/main.ts
  packages/backend/src/middlewares/filter/webSocketException.filter.ts
  packages/backend/src/stock/stock.module.ts
  packages/backend/src/stock/stock.service.ts
Labels: ✨feature, BE

#167 Feature/#32 사용자 테마 변경 및 조회 기능 추가
  packages/backend/src/user/dto/userTheme.response.ts
  packages/backend/src/user/user.controller.ts
  packages/backend/src/user/user.module.ts
  packages/backend/src/user/user.service.spec.ts
  packages/backend/src/user/user.service.ts
Labels: ✨feature, BE

#173 Feature/#34 주식 조회수 기반 리스트 조회 API 기능 구현
  packages/backend/src/stock/decorator/stock.decorator.ts
  packages/backend/src/stock/domain/stockDetail.entity.ts
  packages/backend/src/stock/domain/stockLiveData.entity.ts
  packages/backend/src/stock/dto/stock.Response.ts
  packages/backend/src/stock/stock.controller.ts
  packages/backend/src/stock/stock.service.spec.ts
  packages/backend/src/stock/stock.service.ts
  packages/backend/src/user/user.service.spec.ts
Labels: ✨feature, BE

#175 Feature/#158 - 소유 주식 확인 엔드포인트 구현
  packages/backend/src/auth/session/cookieParser.ts
  packages/backend/src/auth/session/session.guard.ts
  packages/backend/src/common/decorator/user.decorator.ts
  packages/backend/src/configs/session.config.ts
  packages/backend/src/stock/dto/userStock.request.ts
  packages/backend/src/stock/dto/userStock.response.ts
  packages/backend/src/stock/stock.controller.ts
  packages/backend/src/stock/stock.service.spec.ts
  packages/backend/src/stock/stock.service.ts
  packages/backend/src/user/domain/user.entity.ts
Labels: ✨feature, BE

#176 Feature/#37 가격 상승률 기반 주식 리스트 조회 API 기능 구현
  packages/backend/src/stock/stock.controller.ts
  packages/backend/src/stock/stock.service.spec.ts
  packages/backend/src/stock/stock.service.ts
Labels: ✨feature, BE

#177 Feature/#38 가격 하락률 기준 주식 리스트 조회 기능 구현
  packages/backend/src/stock/stock.controller.ts
  packages/backend/src/stock/stock.service.spec.ts
  packages/backend/src/stock/stock.service.ts
Labels: ✨feature, BE

#178 Feature/#10 주식 정보 분, 일, 주, 월, 년 가져오기
  .github/workflows/close-issue.yml
  .husky/commit-msg
  .husky/pre-commit
  packages/backend/package.json
  packages/backend/src/app.module.ts
  packages/backend/src/configs/devTypeormConfig.ts
  packages/backend/src/openapi-scraper/korea-stock-info/dto/master-split.dto.ts
  packages/backend/src/openapi-scraper/korea-stock-info/korea-stock-info.controller.spec.ts
  packages/backend/src/openapi-scraper/korea-stock-info/korea-stock-info.controller.ts
  packages/backend/src/openapi-scraper/korea-stock-info/korea-stock-info.service.ts
  packages/backend/src/openapi-scraper/openapi-scraper.controller.ts
  packages/backend/src/openapi-scraper/openapi-scraper.service.ts
  packages/backend/src/openapi-scraper/openapi-scraper.ts
  packages/backend/src/openapi-scraper/openapi.config.ts
  packages/backend/src/scraper/korea-stock-info/dto/master-download.dto.ts
  packages/backend/src/scraper/korea-stock-info/entities/stock.entity.ts
  packages/backend/src/scraper/korea-stock-info/korea-stock-info.module.ts
  packages/backend/src/scraper/korea-stock-info/korea-stock-info.service.spec.ts
  packages/backend/src/scraper/korea-stock-info/korea-stock-info.service.ts
  packages/backend/src/scraper/openapi/api/openapiMinuteData.api.ts
  packages/backend/src/scraper/openapi/api/openapiPeriodData.api.ts
  packages/backend/src/scraper/openapi/api/openapiToken.api.ts
  packages/backend/src/scraper/openapi/config/openapi.config.ts
  packages/backend/src/scraper/openapi/openapi-scraper.module.ts
  packages/backend/src/scraper/openapi/openapi-scraper.service.ts
  packages/backend/src/scraper/openapi/openapiUtil.api.ts
  packages/backend/src/scraper/openapi/type/openapiMinuteData.type.ts
  packages/backend/src/scraper/openapi/type/openapiPeriodData.ts
  packages/backend/src/scraper/scraper.module.ts
  packages/backend/src/stock-price/stock-price.controller.spec.ts
  packages/backend/src/stock-price/stock-price.controller.ts
  packages/backend/src/stock-price/stock-price.module.ts
  packages/backend/src/stock/domain/stock.entity.ts
  packages/backend/src/stock/domain/stockData.entity.ts
  packages/backend/tsconfig.json
  packages/frontend/Dockerfile
  test.js
  yarn.lock
Labels: ✨feature, BE

#179 Fix/deploy backend dockerfile
  packages/backend/Dockerfile
Labels: :earth_asia: deploy

#186 Fix/endpoint api 엔드포인트로 변경, bigint -> decimal로 변경
  packages/backend/src/app.module.ts
  packages/backend/src/main.ts
  packages/backend/src/scraper/openapi/api/openapiMinuteData.api.ts
  packages/backend/src/scraper/openapi/api/openapiPeriodData.api.ts
  packages/backend/src/scraper/openapi/openapi-scraper.module.ts
  packages/backend/src/scraper/openapi/openapi-scraper.service.ts
  packages/backend/src/stock/domain/stockData.entity.ts
Labels: 📪API, BE

#189 Feature/#98 - 채팅방에 참여할 때 현재 시점부터 일정 개수의 메시지를 가져온다
  packages/backend/src/auth/session/cookieParser.ts
  packages/backend/src/chat/chat.gateway.ts
  packages/backend/src/chat/chat.service.ts
  packages/backend/src/chat/domain/chat.entity.ts
  packages/backend/src/stock/stock.service.spec.ts
Labels: ✨feature, BE

#190 Feature/#99 - 참여한 채팅방에서 이전 기록을 확인할 수 있다.
  packages/backend/src/app.module.ts
  packages/backend/src/auth/session/cookieParser.ts
  packages/backend/src/chat/chat.controller.ts
  packages/backend/src/chat/chat.gateway.ts
  packages/backend/src/chat/chat.module.ts
  packages/backend/src/chat/chat.service.ts
  packages/backend/src/chat/domain/chat.entity.ts
  packages/backend/src/chat/dto/chat.request.ts
  packages/backend/src/chat/dto/chat.response.ts
  packages/backend/src/common/dateEmbedded.entity.ts
  packages/backend/src/configs/swagger.config.ts
  packages/backend/src/main.ts
  packages/backend/src/scraper/openapi/api/openapiMinuteData.api.ts
  packages/backend/src/scraper/openapi/api/openapiPeriodData.api.ts
  packages/backend/src/scraper/openapi/openapi-scraper.module.ts
  packages/backend/src/scraper/openapi/openapi-scraper.service.ts
  packages/backend/src/stock/domain/stockData.entity.ts
  packages/backend/src/stock/stock.service.spec.ts
Labels: ✨feature, BE

#192 Feature/#188 - 검색 UI 구현
  packages/frontend/src/components/layouts/MenuList.tsx
  packages/frontend/src/components/layouts/Sidebar.tsx
  packages/frontend/src/components/layouts/search/Search.tsx
  packages/frontend/src/components/layouts/search/index.ts
  packages/frontend/src/components/ui/button/Button.tsx
  packages/frontend/src/components/ui/input/Input.tsx
  packages/frontend/src/components/ui/input/index.ts
  packages/frontend/src/constants/menuItems.tsx
  packages/frontend/src/hooks/useOutsideClick.ts
  packages/frontend/src/pages/stock-detail/StockDetail.tsx
  packages/frontend/src/pages/stocks/components/StockIndexCard.tsx
  packages/frontend/src/types/menu.ts
Labels: ✨feature, 🎨 html&css, FE

#195 Feature/#194 - 채팅 UI 구현
  packages/frontend/src/assets/like.svg
  packages/frontend/src/pages/stock-detail/ChatPanel.tsx
  packages/frontend/src/pages/stock-detail/components/ChatMessage.tsx
Labels: 🎨 html&css, FE

#196 Feature/#159 - 로그인 UI 구현
  packages/frontend/package.json
  packages/frontend/src/apis/index.ts
  packages/frontend/src/assets/google.png
  packages/frontend/src/assets/kakao.png
  packages/frontend/src/assets/naver.png
  packages/frontend/src/pages/login/Login.tsx
  packages/frontend/src/pages/login/index.ts
  packages/frontend/src/routes/index.tsx
  yarn.lock
Labels: 🎨 html&css, FE

#199 Feature/#104 - 좋아요 순 스크롤 기능 구현
  packages/backend/src/chat/chat.controller.ts
  packages/backend/src/chat/chat.gateway.ts
  packages/backend/src/chat/chat.service.spec.ts
  packages/backend/src/chat/chat.service.ts
  packages/backend/src/chat/domain/chat.entity.ts
  packages/backend/src/stock/stock.controller.ts
  packages/backend/src/user/user.service.spec.ts
Labels: ✨feature, BE

#204 Bug/#202 - 웹 소켓 비어있는 쿠키 에러 수정
  packages/backend/src/auth/session/websocketSession.service.ts
Labels: :lady_beetle: bugfix, BE

#205 Feature/#40 - 주식 가격 상승/하락순, 조회수순 api 호출
  packages/frontend/src/apis/config/index.ts
  packages/frontend/src/apis/queries/stocks/index.ts
  packages/frontend/src/apis/queries/stocks/types.ts
  packages/frontend/src/apis/queries/stocks/useGetStocksByPrice.ts
  packages/frontend/src/apis/queries/stocks/useGetTopViews.ts
  packages/frontend/src/pages/stocks/StockRankingTable.tsx
  packages/frontend/src/pages/stocks/Stocks.tsx
  packages/frontend/src/pages/stocks/components/StockInfoCard.tsx
  packages/frontend/src/styles/theme/darkTheme.ts
Labels: ✨feature, 📪API, FE

#209 Feature/#207 - 주식 controller 엔트포인트 통합
  packages/backend/src/configs/session.config.ts
  packages/backend/src/stock/decorator/stockData.decorator.ts
  packages/backend/src/stock/stock.controller.ts
Labels: ✨feature, BE

#206 Feature/#123 - 주식 조회수 증가 api 연결
  packages/frontend/src/apis/queries/stock-detail/index.ts
  packages/frontend/src/apis/queries/stock-detail/types.ts
  packages/frontend/src/apis/queries/stock-detail/usePostStockView.ts
  packages/frontend/src/pages/stocks/StockRankingTable.tsx
Labels: 📪API, FE

#212 Feature/#211 - sameSite 옵션 수정
  packages/backend/src/configs/session.config.ts
Labels: ✨feature, BE

#217 Feature/#216 - 쿠키 도메인 설정
  packages/backend/src/configs/session.config.ts
Labels: BE

#213 Feature/#52 - 로그인 api 연결
  packages/frontend/src/apis/queries/auth/index.ts
  packages/frontend/src/apis/queries/auth/types.ts
  packages/frontend/src/apis/queries/auth/useGetLoginStatus.ts
  packages/frontend/src/components/layouts/Sidebar.tsx
  packages/frontend/src/pages/login/Login.tsx
  packages/frontend/src/pages/my-page/MyPage.tsx
Labels: 📪API, 🎨 html&css, FE

#219 Feature/#218 - 채팅에 사용자 닉네임 정보 추가
  packages/backend/src/chat/chat.service.ts
  packages/backend/src/chat/dto/chat.response.ts
Labels: ✨feature, BE

#222 Feature/#105 - 채팅 웹소켓 연결
  packages/frontend/package.json
  packages/frontend/src/components/layouts/Sidebar.tsx
  packages/frontend/src/pages/stock-detail/ChatPanel.tsx
  packages/frontend/src/pages/stock-detail/components/ChatMessage.tsx
  packages/frontend/src/pages/stock-detail/components/TextArea.tsx
  packages/frontend/src/sockets/chat.ts
  packages/frontend/src/sockets/config.ts
  packages/frontend/src/sockets/types.ts
  yarn.lock
Labels: ✨feature, 📪API, FE

#225 Bug - 웹소켓 stockId를 넘기지 못하는 문제
  packages/frontend/src/pages/stock-detail/ChatPanel.tsx
  packages/frontend/src/sockets/config.ts
Labels: :lady_beetle: bugfix, FE

#226 fix: 로그인 리다이렉트 url 수정
  packages/frontend/src/pages/login/Login.tsx
Labels: :lady_beetle: bugfix, FE

#227 fix: 로그인 url 이동 시 새로고침 되도록 수정
  packages/frontend/src/pages/login/Login.tsx
Labels: :lady_beetle: bugfix, FE

#228 fix: 웹소켓 커스텀훅 추상화 수정
  packages/frontend/src/pages/stock-detail/ChatPanel.tsx
  packages/frontend/src/sockets/useWebsocket.ts
Labels: :lady_beetle: bugfix, 📪API, FE

#229 fix: 서버 이슈로 목데이터로 잠시 대체
  packages/frontend/src/mocks/stock.json
  packages/frontend/src/pages/stock-detail/StockDetail.tsx
  packages/frontend/src/pages/stocks/StockRankingTable.tsx
  packages/frontend/src/pages/stocks/Stocks.tsx
  packages/frontend/src/routes/index.tsx
  packages/frontend/src/sockets/chat.ts
Labels: FE

#233 filter 삭제, 핵심함수 private 삭제, 우선순위 큐 만들기, websocket 데이터 등록 관련 구조 변경
  .gitignore
  packages/backend/package.json
  packages/backend/src/scraper/openapi/Decorator/openapiException.filter.ts
  packages/backend/src/scraper/openapi/api/openapiDetailData.api.ts
  packages/backend/src/scraper/openapi/api/openapiLiveData.api.ts
  packages/backend/src/scraper/openapi/api/openapiMinuteData.api.ts
  packages/backend/src/scraper/openapi/api/openapiPeriodData.api.ts
  packages/backend/src/scraper/openapi/api/openapiToken.api.ts
  packages/backend/src/scraper/openapi/openapi-scraper.module.ts
  packages/backend/src/scraper/openapi/parse/openapi.parser.spec.ts
  packages/backend/src/scraper/openapi/parse/openapi.parser.ts
  packages/backend/src/scraper/openapi/type/openapiLiveData.type.ts
  packages/backend/src/scraper/openapi/type/openapiPeriodData.ts
  packages/backend/src/scraper/openapi/util/priorityQueue.ts
  packages/backend/src/scraper/openapi/websocketClient.service.ts
  packages/backend/src/stock/dto/stockDetail.response.ts
  packages/backend/src/stock/stockDetail.service.ts
  packages/backend/src/user/user.service.spec.ts
Labels: :lady_beetle: bugfix, 🔨 refactor

#237 Feature/#231 - zod 적용
  packages/frontend/package.json
  packages/frontend/src/apis/queries/auth/schema.ts
  packages/frontend/src/apis/queries/auth/types.ts
  packages/frontend/src/apis/queries/auth/useGetLoginStatus.ts
  packages/frontend/src/apis/queries/stock-detail/index.ts
  packages/frontend/src/apis/queries/stock-detail/schema.ts
  packages/frontend/src/apis/queries/stock-detail/types.ts
  packages/frontend/src/apis/queries/stock-detail/useGetStockDetail.ts
  packages/frontend/src/apis/queries/stock-detail/usePostStockView.ts
  packages/frontend/src/apis/queries/stocks/index.ts
  packages/frontend/src/apis/queries/stocks/schema.ts
  packages/frontend/src/apis/queries/stocks/types.ts
  packages/frontend/src/apis/queries/stocks/useGetStocksByPrice.ts
  packages/frontend/src/apis/queries/stocks/useGetTopViews.ts
  packages/frontend/src/apis/utils/formatZodError.ts
  packages/frontend/src/apis/utils/get.ts
  packages/frontend/src/apis/utils/post.ts
  packages/frontend/src/pages/stock-detail/ChatPanel.tsx
  packages/frontend/src/pages/stock-detail/StockDetail.tsx
  packages/frontend/src/pages/stocks/StockRankingTable.tsx
  packages/frontend/src/pages/stocks/Stocks.tsx
  packages/frontend/src/sockets/schema.ts
  packages/frontend/src/sockets/types.ts
  yarn.lock
Labels: ✨feature, 📪API, FE

#238 Feature/#230 - 테스터 유저 기능 구현
  packages/backend/package.json
  packages/backend/src/auth/auth.module.ts
  packages/backend/src/auth/google/strategy/google.strategy.ts
  packages/backend/src/auth/tester/guard/tester.guard.ts
  packages/backend/src/auth/tester/strategy/tester.strategy.ts
  packages/backend/src/auth/tester/testerAuth.controller.ts
  packages/backend/src/auth/tester/testerAuth.service.ts
  packages/backend/src/user/user.service.ts
  yarn.lock
Labels: ✨feature, BE

#240 Bug/#235 websocket 버그 해결, token db에 저장
  packages/backend/src/configs/typeormConfig.ts
  packages/backend/src/scraper/domain/openapiToken.entity.ts
  packages/backend/src/scraper/openapi/api/openapiDetailData.api.ts
  packages/backend/src/scraper/openapi/api/openapiLiveData.api.ts
  packages/backend/src/scraper/openapi/api/openapiMinuteData.api.ts
  packages/backend/src/scraper/openapi/api/openapiPeriodData.api.ts
  packages/backend/src/scraper/openapi/api/openapiToken.api.ts
  packages/backend/src/scraper/openapi/openapi-scraper.module.ts
  packages/backend/src/scraper/openapi/util/priorityQueue.ts
  packages/backend/src/scraper/openapi/websocketClient.service.ts
  packages/backend/src/stock/domain/stock.entity.ts
Labels: :lady_beetle: bugfix, 🔨 refactor, BE

#244 Feature/#241 - 알림창 관련 UI 구현
  packages/frontend/src/assets/date.svg
  packages/frontend/src/assets/flag.svg
  packages/frontend/src/assets/small-bell.svg
  packages/frontend/src/components/layouts/Layout.tsx
  packages/frontend/src/components/layouts/Sidebar.tsx
  packages/frontend/src/components/layouts/alarm/Alarm.tsx
  packages/frontend/src/components/layouts/alarm/index.ts
  packages/frontend/src/components/ui/alarm/Alarm.tsx
  packages/frontend/src/components/ui/alarm/index.ts
  packages/frontend/src/constants/METRIC_DETAILS.ts
  packages/frontend/src/constants/alarmOptions.tsx
  packages/frontend/src/index.css
  packages/frontend/src/mocks/alarm.json
  packages/frontend/src/pages/my-page/AlarmInfo.tsx
  packages/frontend/src/pages/my-page/MyPage.tsx
  packages/frontend/src/pages/my-page/StockInfo.tsx
  packages/frontend/src/pages/stock-detail/AddAlarmForm.tsx
  packages/frontend/src/pages/stock-detail/ChatPanel.tsx
  packages/frontend/src/pages/stock-detail/NotificationPanel.tsx
  packages/frontend/src/pages/stock-detail/StockDetail.tsx
  packages/frontend/src/pages/stock-detail/StockMetricsPanel.tsx
  packages/frontend/src/pages/stock-detail/index.ts
  packages/frontend/src/utils/getCurrentDate.ts
Labels: 🎨 html&css, FE

#246 livedata 수집 추가 + openapi로 장시간,마감 변경 로직, token을 주입할 수 있게 변경
  packages/backend/src/configs/typeormConfig.ts
  packages/backend/src/scraper/openapi/api/openapiDetailData.api.ts
  packages/backend/src/scraper/openapi/api/openapiLiveData.api.ts
  packages/backend/src/scraper/openapi/api/openapiMinuteData.api.ts
  packages/backend/src/scraper/openapi/api/openapiPeriodData.api.ts
  packages/backend/src/scraper/openapi/api/openapiToken.api.ts
  packages/backend/src/scraper/openapi/liveData.service.ts
  packages/backend/src/scraper/openapi/openapi-scraper.module.ts
  packages/backend/src/scraper/openapi/type/openapiLiveData.type.ts
  packages/backend/src/scraper/openapi/type/openapiUtil.type.ts
  packages/backend/src/scraper/openapi/websocket/websocketClient.websocket.ts
  packages/backend/src/scraper/openapi/websocketClient.service.ts
  packages/backend/src/stock/domain/stockLiveData.entity.ts
  packages/backend/src/stock/stock.gateway.ts
  packages/backend/src/stock/stock.module.ts
Labels: ✨feature, 🔨 refactor, BE

#256 Bug/#250 stock data 문제 해결
  packages/backend/src/scraper/openapi/api/openapiDetailData.api.ts
  packages/backend/src/scraper/openapi/api/openapiNewDetailData.api.ts
  packages/backend/src/scraper/openapi/api/openapiPeriodData.api.ts
  packages/backend/src/scraper/openapi/api/openapiToken.api.ts
  packages/backend/src/scraper/openapi/config/openapi.config.ts
  packages/backend/src/scraper/openapi/liveData.service.ts
  packages/backend/src/scraper/openapi/type/openapiDetailData.type.ts
  packages/backend/src/scraper/openapi/type/openapiNewDetailData.type.ts
  packages/backend/src/scraper/openapi/websocket/websocketClient.websocket.ts
  packages/backend/src/stock/domain/stockData.entity.ts
Labels: :lady_beetle: bugfix, BE

#254 Feature/#245 - 주식 검색, 그래프 조회 구현
  packages/frontend/package.json
  packages/frontend/src/apis/queries/stock-detail/usePostStockView.ts
  packages/frontend/src/apis/queries/stocks/schema.ts
  packages/frontend/src/apis/queries/stocks/useGetSearchStocks.ts
  packages/frontend/src/apis/queries/stocks/useGetStocksPriceSeries.ts
  packages/frontend/src/apis/utils/get.ts
  packages/frontend/src/apis/utils/post.ts
  packages/frontend/src/components/layouts/search/Search.tsx
  packages/frontend/src/components/layouts/search/SearchResults.tsx
  packages/frontend/src/components/lottie/loading-animation.json
  packages/frontend/src/constants/timeUnit.ts
  packages/frontend/src/pages/my-page/AlarmInfo.tsx
  packages/frontend/src/pages/stock-detail/NotificationPanel.tsx
  packages/frontend/src/pages/stock-detail/TradingChart.tsx
  packages/frontend/src/pages/stock-detail/components/RadioButton.tsx
  packages/frontend/src/pages/stock-detail/hooks/useChart.ts
  packages/frontend/src/utils/getHistogramColorData.ts
  yarn.lock
Labels: ✨feature, 📪API, FE

#260 Feature/#253 - 가격 상승률 및 하락률 데이터 수집
  packages/backend/src/auth/google/googleAuth.controller.ts
  packages/backend/src/scraper/openapi/api/openapiFluctuationData.api.ts
  packages/backend/src/scraper/openapi/constants/query.ts
  packages/backend/src/scraper/openapi/openapi-scraper.module.ts
  packages/backend/src/scraper/openapi/type/openapiUtil.type.ts
  packages/backend/src/stock/domain/FluctuationRankStock.entity.ts
  packages/backend/src/stock/domain/stock.entity.ts
  packages/backend/src/stock/dto/stock.response.ts
  packages/backend/src/stock/stock.service.ts
Labels: ✨feature, BE

#270 Feature/#268 - 주식 소유 리스트 조회 구현 및 삭제 로직 변경
  packages/backend/src/stock/domain/userStock.entity.ts
  packages/backend/src/stock/dto/userStock.request.ts
  packages/backend/src/stock/dto/userStock.response.ts
  packages/backend/src/stock/stock.controller.ts
  packages/backend/src/stock/stock.service.spec.ts
  packages/backend/src/stock/stock.service.ts
Labels: ✨feature, BE

#272 Feature/#271 - 변동률 데이터 조회 시 라이브 데이터도 조회
  packages/backend/src/auth/google/googleAuth.controller.ts
  packages/backend/src/scraper/openapi/api/openapiDetailData.api.ts
  packages/backend/src/scraper/openapi/api/openapiFluctuationData.api.ts
Labels: ✨feature, BE

#269 Bug/#267 - typeorm 기능으로 exist 확인, token 발급주기 단축(12시간)
  packages/backend/src/scraper/openapi/api/openapi.abstract.ts
  packages/backend/src/scraper/openapi/api/openapiDetailData.api.ts
  packages/backend/src/scraper/openapi/api/openapiIndex.api.ts
  packages/backend/src/scraper/openapi/api/openapiLiveData.api.ts
  packages/backend/src/scraper/openapi/api/openapiNewDetailData.api.ts
  packages/backend/src/scraper/openapi/api/openapiToken.api.ts
  packages/backend/src/scraper/openapi/liveData.service.ts
  packages/backend/src/scraper/openapi/type/openapiIndex.type.ts
  packages/backend/src/scraper/openapi/type/openapiNewDetailData.type.ts
  packages/backend/src/scraper/openapi/type/openapiUtil.type.ts
Labels: :lady_beetle: bugfix, 🔨 refactor, BE

#274 Feature/#273 - 배포환경 칼럼 에러 문제 해결
  packages/backend/src/chat/chat.service.ts
  packages/backend/src/scraper/openapi/api/openapiFluctuationData.api.ts
  packages/backend/src/stock/dto/stock.response.ts
  packages/backend/src/stock/stock.service.ts
  packages/backend/src/user/user.service.ts
Labels: :lady_beetle: bugfix, BE

#276 Feature/#62 - 로그아웃 기능 구현
  packages/backend/src/auth/auth.controller.ts
  packages/backend/src/auth/auth.module.ts
  packages/backend/src/auth/google/googleAuth.controller.ts
  packages/backend/src/main.ts
  packages/backend/src/stock/dto/stock.response.ts
  packages/backend/src/stock/stock.service.ts
  packages/backend/src/user/dto/User.response.ts
  packages/backend/src/user/dto/user.request.ts
  packages/backend/src/user/dto/user.response.ts
  packages/backend/src/user/user.controller.ts
  packages/backend/src/user/user.service.ts
Labels: ✨feature, BE

#281 Feature/#280 - 가격 상승률 및 하락률 통합 조회 API 구현
  packages/backend/src/stock/stock.controller.ts
  packages/backend/src/stock/stock.service.ts
Labels: ✨feature, BE

#288 Bug/#287 - 변동률 조회시 정해진 길이를 받지 않는 현상 수정
  packages/backend/src/stock/stock.service.ts
Labels: :lady_beetle: bugfix, BE

#296 Feature/#295 - 자잘한 UI 에러 수정
  packages/frontend/src/apis/queries/chat/usePostChatLike.ts
  packages/frontend/src/components/layouts/Sidebar.tsx
  packages/frontend/src/constants/chatPlaceholder.ts
  packages/frontend/src/constants/menuItems.tsx
  packages/frontend/src/pages/login/Login.tsx
  packages/frontend/src/pages/my-page/StockInfo.tsx
  packages/frontend/src/pages/stock-detail/ChatPanel.tsx
  packages/frontend/src/pages/stock-detail/StockDetail.tsx
  packages/frontend/src/pages/stock-detail/TradingChart.tsx
  yarn.lock
Labels: :lady_beetle: bugfix, FE

#294 Refactor/#284 - 웹소켓 리팩토링, livedata 서빙문제 해결
  packages/backend/package.json
  packages/backend/src/app.module.ts
  packages/backend/src/scraper/openapi/api/openapiFluctuationData.api.ts
  packages/backend/src/scraper/openapi/api/openapiLiveData.api.ts
  packages/backend/src/scraper/openapi/api/openapiRankView.api.ts
  packages/backend/src/scraper/openapi/liveData.service.ts
  packages/backend/src/scraper/openapi/openapi-scraper.module.ts
  packages/backend/src/scraper/openapi/type/openapiDetailData.type.ts
  packages/backend/src/scraper/openapi/type/openapiIndex.type.ts
  packages/backend/src/scraper/openapi/type/openapiMinuteData.type.ts
  packages/backend/src/scraper/openapi/type/openapiPeriodData.type.ts
  packages/backend/src/scraper/openapi/websocket/websocketClient.websocket.ts
  packages/backend/src/scraper/scraper.module.ts
  packages/backend/src/stock/stock.gateway.ts
  packages/backend/src/stock/stock.module.ts
  packages/backend/src/stock/stockLiveData.subscriber.ts
  packages/backend/src/user/user.controller.ts
  yarn.lock
Labels: :lady_beetle: bugfix, 🔨 refactor, BE

#302 Feature/#297 - 가격 등락률 순 api 추가
  packages/frontend/package.json
  packages/frontend/src/App.tsx
  packages/frontend/src/apis/queries/stocks/schema.ts
  packages/frontend/src/apis/queries/stocks/useGetStocksByPrice.ts
  packages/frontend/src/pages/stocks/StockRankingTable.tsx
  yarn.lock
Labels: 📪API, FE

#305 Feature/#30 - 다크모드 구현
  packages/frontend/src/apis/queries/auth/schema.ts
  packages/frontend/src/apis/queries/user/index.ts
  packages/frontend/src/apis/queries/user/schema.ts
  packages/frontend/src/apis/queries/user/useGetUserInfo.ts
  packages/frontend/src/apis/queries/user/useGetUserStock.ts
  packages/frontend/src/apis/queries/user/usePostUserNickname.ts
  packages/frontend/src/assets/google.png
  packages/frontend/src/assets/google.svg
  packages/frontend/src/components/layouts/Layout.tsx
  packages/frontend/src/components/layouts/Sidebar.tsx
  packages/frontend/src/components/ui/alarm/Alarm.tsx
  packages/frontend/src/components/ui/input/Input.tsx
  packages/frontend/src/index.css
  packages/frontend/src/pages/login/Login.tsx
  packages/frontend/src/pages/my-page/StockInfo.tsx
  packages/frontend/src/pages/my-page/UserInfo.tsx
  packages/frontend/src/pages/stock-detail/AddAlarmForm.tsx
  packages/frontend/src/pages/stock-detail/components/TextArea.tsx
  packages/frontend/src/styles/theme/darkTheme.ts
  packages/frontend/src/styles/theme/lightTheme.ts
  packages/frontend/src/utils/getHistogramColorData.ts
  packages/frontend/tailwind.config.ts
Labels: ✨feature, 🎨 html&css, FE
